name = "chant-stand"
compatibility_date = "2024-12-01"
pages_build_output_dir = "public"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "chant_stand_db"
database_id = "6a8dc4af-91ff-47ab-bc12-87842d24f445"
